### ISSUE TITLE
HelloZero is not work well

### ISSUE THREAD

**Issue by CalunVier** [zeronet-conservancy/zeronet-conservancy#35] opened 2022-03-18 19:34 UTC
### Step 1: Please describe your environment

  * ZeroNet version: 2022.03.19 zeronet-conservancy master d1198e80e21a11ec28ce211da4e7a71c97c4f9bb
  * Operating system: Android 12 with Termux
  * Web browser: Google Chrome
  * Tor status: disabled
  * Opened port: no
  * Special configuration: no

### Step 2: Describe the problem:
the files page and stats page not work well
#### Steps to reproduce:

  1. start zeronet-conservancy
  2. open http://127.0.0.1:43110/ in browser
  3. click files or stats on the side bar

#### Expected Results:

  * Just like that the original HelloZero.

**Comment by caryoscelus** [comment] 2022-03-19 16:45
> the files page and stats page not work well

can you provide any details? did you test both versions in the same environment?

for me both original Hello page and conservancy one haven't worked perfectly with "files" and "stats" tabs. i have to reload the page after clicking on them to see anything

so far conservancy Hello page only differs from original in branding and startup sites, so the only thing that could lead to different behaviour is different permissions (but latest conservancy grants ADMIN permission to the new page..). or some weird bug

**Comment by CalunVier** [comment] 2022-03-19 17:44
> > the files page and stats page not work well
> 
> can you provide any details? did you test both versions in the same environment?
> 
> for me both original Hello page and conservancy one haven't worked perfectly with "files" and "stats" tabs. i have to reload the page after clicking on them to see anything
> 
> so far conservancy Hello page only differs from original in branding and startup sites, so the only thing that could lead to different behaviour is different permissions (but latest conservancy grants ADMIN permission to the new page..). or some weird bug

I have created a private chat on matrix. Let's we talk in there for that i can send photos easily.

**Comment by caryoscelus** [comment] 2022-03-19 19:24
@CalunVier thanks for reporting!

in case anyone encounter this before it's fixed: the issue is that admin permissions are not added to the new admin page (in certain cases)

**Comment by caryoscelus** [comment] 2022-04-12 07:09
this has been fixed by updating admin page ─ it now asks for ADMIN permission

**Closed by caryoscelus** 2022-04-12 07:09 UTC
